name: Doc build

on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:

jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9  # v1
        with:
          build: true
          test: false
          lint: false
      - run: lake build Geb:docs
